version: "3"

services:
  backend:
    image: ${DOCKER_USER}/mosoo_spring:latest
    container_name: mosoo_spring
    ports:
      - 8080:8080
    environment:
      AWS_S3_AK: ${AWS_S3_AK}
      AWS_S3_SK: ${AWS_S3_SK}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DEPLOY_FRONT_URL: ${DEPLOY_FRONT_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      REDIS_HOST: redis # Redis 호스트 설정
      REDIS_PORT: 6379  # Redis 포트 설정
      impKey: ${impKey}
      impSecret: ${impSecret}
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  redis_data:
